services:
  ia_check_venv:
    hostname:         ia_check_venv.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_check_venv:latest
    #    -           ia_check_venv:latest
    #    - innovanon/ia_check_venv
    #    -           ia_check_venv
    image:            innovanon/ia_check_venv
    restart:          no
    logging:
      driver:         syslog   
