services:
  ia_check_venv:
    hostname:         ia_check_venv.innovanon.com
    build:
      context:        .
      tags:
        - ia_check_venv:latest
    restart:          no
    logging:
      driver:         syslog   
